/* Copyright 2013 Antonio Collarino, Vincenzo Barone

This file is part of Music Feature Extractor (MFE).

Music Feature Extractor (MFE) is free software; you can redistribute it 
and/or modify it under the terms of the GNU Lesser General Public License 
as published by the Free Software Foundation; either version 3 of the 
License, or (at your option) any later version.

Music Feature Extractor (MFE) is distributed in the hope that it will be 
useful, but WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser 
General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with Music Feature Extractor (MFE).  If not, see 
http://www.gnu.org/licenses/.  */

// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.15 at 11:38:08 AM CEST 
//


package albumArtifacts;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AlbumType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AlbumType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="XMLFileCreation" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="artist" type="{https://github.com/AntonioCollarino/MusicFeatureExtractor.git}artistType" minOccurs="0"/>
 *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="country" type="{https://github.com/AntonioCollarino/MusicFeatureExtractor.git}countryType" minOccurs="0"/>
 *         &lt;element name="trackCount" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *         &lt;element name="songList" type="{https://github.com/AntonioCollarino/MusicFeatureExtractor.git}songListType" minOccurs="0"/>
 *         &lt;element name="mediumList" type="{https://github.com/AntonioCollarino/MusicFeatureExtractor.git}mediumListType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="mbArtistID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="mbAlbumID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AlbumType", propOrder = {
    "xmlFileCreation",
    "title",
    "artist",
    "date",
    "country",
    "trackCount",
    "songList",
    "mediumList"
})
public class AlbumType {

    @XmlElement(name = "XMLFileCreation", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar xmlFileCreation;
    @XmlElement(required = true)
    protected String title;
    protected ArtistType artist;
    protected String date;
    protected String country;
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger trackCount;
    protected SongListType songList;
    protected MediumListType mediumList;
    @XmlAttribute(name = "mbArtistID")
    protected String mbArtistID;
    @XmlAttribute(name = "mbAlbumID")
    protected String mbAlbumID;

    /**
     * Gets the value of the xmlFileCreation property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getXMLFileCreation() {
        return xmlFileCreation;
    }

    /**
     * Sets the value of the xmlFileCreation property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setXMLFileCreation(XMLGregorianCalendar value) {
        this.xmlFileCreation = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the artist property.
     * 
     * @return
     *     possible object is
     *     {@link ArtistType }
     *     
     */
    public ArtistType getArtist() {
        return artist;
    }

    /**
     * Sets the value of the artist property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArtistType }
     *     
     */
    public void setArtist(ArtistType value) {
        this.artist = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDate(String value) {
        this.date = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the trackCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTrackCount() {
        return trackCount;
    }

    /**
     * Sets the value of the trackCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTrackCount(BigInteger value) {
        this.trackCount = value;
    }

    /**
     * Gets the value of the songList property.
     * 
     * @return
     *     possible object is
     *     {@link SongListType }
     *     
     */
    public SongListType getSongList() {
        return songList;
    }

    /**
     * Sets the value of the songList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SongListType }
     *     
     */
    public void setSongList(SongListType value) {
        this.songList = value;
    }

    /**
     * Gets the value of the mediumList property.
     * 
     * @return
     *     possible object is
     *     {@link MediumListType }
     *     
     */
    public MediumListType getMediumList() {
        return mediumList;
    }

    /**
     * Sets the value of the mediumList property.
     * 
     * @param value
     *     allowed object is
     *     {@link MediumListType }
     *     
     */
    public void setMediumList(MediumListType value) {
        this.mediumList = value;
    }

    /**
     * Gets the value of the mbArtistID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMbArtistID() {
        return mbArtistID;
    }

    /**
     * Sets the value of the mbArtistID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMbArtistID(String value) {
        this.mbArtistID = value;
    }

    /**
     * Gets the value of the mbAlbumID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMbAlbumID() {
        return mbAlbumID;
    }

    /**
     * Sets the value of the mbAlbumID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMbAlbumID(String value) {
        this.mbAlbumID = value;
    }

}
