//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.11 at 06:38:10 PM CEST 
//


package artistArtifacts;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ArtistType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArtistType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="XMLFileCreation" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="gender" type="{https://github.com/AntonioCollarino/MusicFeatureExtractor.git}genderType" minOccurs="0"/>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="country" type="{https://github.com/AntonioCollarino/MusicFeatureExtractor.git}countryType" minOccurs="0"/>
 *         &lt;element name="begin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ended" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="end" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="disambiguation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="aliasList" type="{https://github.com/AntonioCollarino/MusicFeatureExtractor.git}aliasListType" minOccurs="0"/>
 *         &lt;element name="biography" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="albumList" type="{https://github.com/AntonioCollarino/MusicFeatureExtractor.git}albumListType" minOccurs="0"/>
 *         &lt;element name="linkList" type="{https://github.com/AntonioCollarino/MusicFeatureExtractor.git}linkListType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="mbArtistID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArtistType", propOrder = {
    "xmlFileCreation",
    "name",
    "gender",
    "type",
    "country",
    "begin",
    "ended",
    "end",
    "disambiguation",
    "aliasList",
    "biography",
    "albumList",
    "linkList"
})
public class ArtistType {

    @XmlElement(name = "XMLFileCreation", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar xmlFileCreation;
    @XmlElement(required = true)
    protected String name;
    protected String gender;
    protected String type;
    protected String country;
    protected String begin;
    protected Boolean ended;
    protected String end;
    protected String disambiguation;
    protected AliasListType aliasList;
    protected String biography;
    protected AlbumListType albumList;
    protected LinkListType linkList;
    @XmlAttribute(name = "mbArtistID")
    protected String mbArtistID;

    /**
     * Gets the value of the xmlFileCreation property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getXMLFileCreation() {
        return xmlFileCreation;
    }

    /**
     * Sets the value of the xmlFileCreation property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setXMLFileCreation(XMLGregorianCalendar value) {
        this.xmlFileCreation = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the begin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBegin() {
        return begin;
    }

    /**
     * Sets the value of the begin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBegin(String value) {
        this.begin = value;
    }

    /**
     * Gets the value of the ended property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEnded() {
        return ended;
    }

    /**
     * Sets the value of the ended property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnded(Boolean value) {
        this.ended = value;
    }

    /**
     * Gets the value of the end property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnd() {
        return end;
    }

    /**
     * Sets the value of the end property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnd(String value) {
        this.end = value;
    }

    /**
     * Gets the value of the disambiguation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisambiguation() {
        return disambiguation;
    }

    /**
     * Sets the value of the disambiguation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisambiguation(String value) {
        this.disambiguation = value;
    }

    /**
     * Gets the value of the aliasList property.
     * 
     * @return
     *     possible object is
     *     {@link AliasListType }
     *     
     */
    public AliasListType getAliasList() {
        return aliasList;
    }

    /**
     * Sets the value of the aliasList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AliasListType }
     *     
     */
    public void setAliasList(AliasListType value) {
        this.aliasList = value;
    }

    /**
     * Gets the value of the biography property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBiography() {
        return biography;
    }

    /**
     * Sets the value of the biography property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBiography(String value) {
        this.biography = value;
    }

    /**
     * Gets the value of the albumList property.
     * 
     * @return
     *     possible object is
     *     {@link AlbumListType }
     *     
     */
    public AlbumListType getAlbumList() {
        return albumList;
    }

    /**
     * Sets the value of the albumList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlbumListType }
     *     
     */
    public void setAlbumList(AlbumListType value) {
        this.albumList = value;
    }

    /**
     * Gets the value of the linkList property.
     * 
     * @return
     *     possible object is
     *     {@link LinkListType }
     *     
     */
    public LinkListType getLinkList() {
        return linkList;
    }

    /**
     * Sets the value of the linkList property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkListType }
     *     
     */
    public void setLinkList(LinkListType value) {
        this.linkList = value;
    }

    /**
     * Gets the value of the mbArtistID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMbArtistID() {
        return mbArtistID;
    }

    /**
     * Sets the value of the mbArtistID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMbArtistID(String value) {
        this.mbArtistID = value;
    }

}
