//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.16 at 09:14:10 PM CEST 
//


package mfeArtifacts.setup;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mfeArtifacts.setup package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MFESetup_QNAME = new QName("https://github.com/AntonioCollarino/MusicFeatureExtractor.git", "MFESetup");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mfeArtifacts.setup
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AuthorType }
     * 
     */
    public AuthorType createAuthorType() {
        return new AuthorType();
    }

    /**
     * Create an instance of {@link MFESetupType }
     * 
     */
    public MFESetupType createMFESetupType() {
        return new MFESetupType();
    }

    /**
     * Create an instance of {@link FlagValueType }
     * 
     */
    public FlagValueType createFlagValueType() {
        return new FlagValueType();
    }

    /**
     * Create an instance of {@link PossibleCommandType }
     * 
     */
    public PossibleCommandType createPossibleCommandType() {
        return new PossibleCommandType();
    }

    /**
     * Create an instance of {@link FlagType }
     * 
     */
    public FlagType createFlagType() {
        return new FlagType();
    }

    /**
     * Create an instance of {@link AuthorType.Author }
     * 
     */
    public AuthorType.Author createAuthorTypeAuthor() {
        return new AuthorType.Author();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MFESetupType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://github.com/AntonioCollarino/MusicFeatureExtractor.git", name = "MFESetup")
    public JAXBElement<MFESetupType> createMFESetup(MFESetupType value) {
        return new JAXBElement<MFESetupType>(_MFESetup_QNAME, MFESetupType.class, null, value);
    }

}
