//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.15 at 11:38:35 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://github.com/AntonioCollarino/MusicFeatureExtractor.git", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package songArtifacts.highLevel;
