//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.15 at 01:48:07 PM CEST 
//


package songArtifacts.lowLevel;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the songArtifacts.lowLevel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SongMetadata_QNAME = new QName("https://github.com/AntonioCollarino/MusicFeatureExtractor.git", "SongMetadata");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: songArtifacts.lowLevel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SongType }
     * 
     */
    public SongType createSongType() {
        return new SongType();
    }

    /**
     * Create an instance of {@link RowType }
     * 
     */
    public RowType createRowType() {
        return new RowType();
    }

    /**
     * Create an instance of {@link RhythmHistogramType }
     * 
     */
    public RhythmHistogramType createRhythmHistogramType() {
        return new RhythmHistogramType();
    }

    /**
     * Create an instance of {@link SsdType }
     * 
     */
    public SsdType createSsdType() {
        return new SsdType();
    }

    /**
     * Create an instance of {@link RhythmPatternType }
     * 
     */
    public RhythmPatternType createRhythmPatternType() {
        return new RhythmPatternType();
    }

    /**
     * Create an instance of {@link StatisticalSpectrumDescriptorType }
     * 
     */
    public StatisticalSpectrumDescriptorType createStatisticalSpectrumDescriptorType() {
        return new StatisticalSpectrumDescriptorType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SongType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://github.com/AntonioCollarino/MusicFeatureExtractor.git", name = "SongMetadata")
    public JAXBElement<SongType> createSongMetadata(SongType value) {
        return new JAXBElement<SongType>(_SongMetadata_QNAME, SongType.class, null, value);
    }

}
